# Uncommented these options as needed.
# To learn more about these config options, check out the OS & Device Configuration documentation.
# http://developer.wildernesslabs.co/Meadow/Meadow.OS/Configuration/OS_Device_Configuration/

Device:
  # Name of the device on the network.
  Name: Meadow_SampleApp

Coprocessor:
    # Should the ESP32 automatically attempt to connect to an access point at startup?
    # If set to true, wifi.config.yaml credentials must be stored in the device.
    AutomaticallyStartNetwork: true
    # Should the ESP32 automatically reconnect to the configured access point?
    AutomaticallyReconnect: true
    # Maximum number of retry attempts for connections etc. before an error code is returned.
    MaximumRetryCount: 9999

# Network configuration.
Network:
    # Automatically attempt to get the time at startup?
    GetNetworkTimeAtStartup: true
    # Time synchronization period in seconds.
    NtpRefreshPeriodSeconds: 600
    # Name of the NTP servers.
    NtpServers:
        - 0.pool.ntp.org
        - 1.pool.ntp.org
        - 2.pool.ntp.org
        - 3.pool.ntp.org
#  Interfaces:
#    - Name: Ethernet
#      UseDHCP: false
#      IPAddress: 192.168.1.60
#      NetMask: 255.255.255.0
#      Gateway: 192.168.1.254
#    - Name: WiFi
#      UseDHCP: true
#      IPAddress:
#      NetMask:
#      Gateway:

    # Which interface should be used?
    DefaultInterface: WiFi

  # IP addresses of the DNS servers.
#  DnsServers:
#    - 1.1.1.1
#    - 8.8.8.8